name: build and publish
on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: aniftyco/php
            context: php
          - image: aniftyco/laravel
            context: laravel
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKER_HUB_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          - name: Build and push
            uses: docker/build-push-action@v4
            with:
              context: ${{ matrix.context }}
              file: ${{ matrix.context }}/Dockerfile
              push: true
              tags: ${{ matrix.image }}:latest
